SELECT * FROM NB_FEM_FIF_STG@FCMOMDEV;
SELECT * FROM WM_GL_HEADERS@FCMOMDEV;
SELECT * FROM WM_GL_LINES@FCMOMDEV;
SELECT * FROM WM_CFG_CR_WMS@FCMOMDEV;
SELECT * FROM GL.GL_INTERFACE@FCEBSDEV;
SELECT * FROM WM_LOG_ERROR@FCWMLOGDEV;
SELECT * FROM WM_LOG_RUN@FCWMLOGDEV;
SELECT * FROM WM_LOG_THREAD@FCWMLOGDEV;